# Learning parameters
LR: 2.5e-4
NUM_ENVS: 4
NUM_STEPS: 128
TOTAL_TIMESTEPS: 500000
UPDATE_EPOCHS: 4
MINIBATCH_SIZE: 32

# Discount factors
GAMMA: 0.99
GAE_LAMBDA: 0.95

# PPO parameters
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: "tanh"

# Environment
ENV_NAME: "MiniGrid-Empty-5x5-v0"
OBS_SHAPE: [5, 5, 3]
NUM_ACTIONS: 7  # Updated to match MiniGrid's actual action space
